name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:

  docker:
    runs-on: ubuntu-latest
    env:
      HASHLINK_VERSION: "1.13"
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push hl only image
        uses: docker/build-push-action@v5
        with:
          build-args: |
            HASHLINK_VERSION=${{ env.HASHLINK_VERSION }}
          file: Dockerfile
          push: true
          tags: |
            alexhath/haxe-hl:latest
            alexhath/haxe-hl:${{ env.HASHLINK_VERSION }}
      -
        name: Build and push hl heaps image
        uses: docker/build-push-action@v5
        with:
          build-args: |
            HASHLINK_VERSION=${{ env.HASHLINK_VERSION }}
          file: Dockerfile.heaps
          push: true
          tags: |
            alexhath/haxe-hl:heaps-latest
            alexhath/haxe-hl:heaps-${{ env.HASHLINK_VERSION }}
      -
        name: Build and push devc hl heaps image
        uses: docker/build-push-action@v5
        with:
          build-args: |
            HASHLINK_VERSION=${{ env.HASHLINK_VERSION }}
          file: Dockerfile.devc
          push: true
          tags: |
            alexhath/haxe-hl:devc-latest
            alexhath/haxe-hl:devc-${{ env.HASHLINK_VERSION }}
